select
    _id as patient_id,
    tenantId as tenant_id,
    userId as user_id,
    status,
    tier,
    tierId as tier_id,
    isVip as is_vip,
    doctorIds as doctor_ids,
    protocol,
    protocolId as protocol_id,
    protocolIds as protocol_ids,
    lastVisit as last_visit,
    nextVisit as next_visit,
    labResults as lab_results,
    medicalHistory as medical_history,
    medicalHistoryDetails as medical_history_details,
    allergies,
    medications,
    documents,
    familyHistory as family_history,
    dosesHistory as doses_history,
    contraindications,
    chronicConditions as chronic_conditions,
    EHR,
    Lifestyle,
    dietPlan as diet_plan,
    dietaryAssessment as dietary_assessment,
    isSoftDeleted as is_soft_deleted,
    createdBy as created_by,
    createdAt as created_at,
    updatedAt as updated_at
from {{ source('techtrax_raw', 'patients') }}
qualify row_number() over (partition by _id order by updatedAt desc) = 1
